### ISSUE TITLE
update-command-not-found should fail if apt-file is not found

### ISSUE THREAD

**Issue by Liz4v** [zyga/command-not-found#6]
https://raspberrypi.stackexchange.com/q/75376/65319

**Comment by zyga** [comment]
Hello, thank you for reporting this issue.

Unfortunately this is not the same command-not-found you think about. There's about half a dozen implementations by various distributions. Last time I checked I didn't use apt-file at all. It is possible that the Debian implementation that a derivative of is used on Raspberry Pi is actually using it.

Some people I know are working on unifying various implementation but this project may fail or take very long time (or both). I will let them know about this issue but otherwise I'd like to close it.
